name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: wget -o index.html https://www.pixiv.net/ranking.php?mode=daily&date=20210919&format=json
      run: wget -o index.html https://www.pixiv.net/ranking.php?mode=daily&date=20210919&format=json
    - name: cat index.html
      run: cat index.html
