name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clearing all the Files
      run: rm ./* -r
    - name: Cloning Codes
      run: git clone https://github.com/LittleYang0531/bilibili.git
    - name: Installing Dependence
      run: sudo apt install php php-curl zip -y
    - name: Downloading Your Photos
      run: php ./bilibili/spider.php 795196
    - name: Removing Codes
      run: rm bilibili -r
    - name: Zipping Your Files
      run: zip Photo.zip ./*
    - name: Upload Your Photos
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Upload
        path: ./Photo.zip
    - name: rm ./* -r
      run: rm ./* -r
