name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: sudo apt install net-tools -y
      run: sudo apt install net-tools -y
    - name: ifconfig
      run: ifconfig
    - name: ls /etc/nginx/sites-enabled
      run: ls /etc/nginx/sites-enabled
