name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ls /proc
      run: ls /proc
    - name: cat /proc/cpuinfo
      run: car /proc/cpuinfo
