# This is a basic workflow to help you get started with Actions

name: gcc-build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  VERSION: 13
  TYPE: basepoints

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Display gcc version
        run: echo gcc-$TYPE-$VERSION
      - name: Test artifact
        run: touch gcc-$TYPE-$VERSION.deb
      - name: Upload archifect
        uses: actions/upload-artifact@v3.1.0
        with:
          name: gcc-$TYPE-$VERSION.deb
          path: gcc-$TYPE-$VERSION.deb
      - name: Download gcc source code from https://github.com/gcc-mirror/gcc
        run: wget https://github.com/gcc-mirror/gcc/archive/refs/tags/$TYPE/gcc-$VERSION.tar.gz -O gcc.tar.gz
      - name: Extract source code
        run: |
          tar -xvf gcc.tar.gz
          mv gcc-$TYPE-gcc-$VERSION gcc-$VERSION
      - name: Download dependences
        run: |
          cd gcc-$VERSION
          ./contrib/download_prerequisites
      - name: Prepare for build environment
        run: mkdir gcc-build-$VERSION
      - name: Check system environment
        run: |
          cd gcc-build-$VERSION
          ../gcc-$VERSION/configure --enable-checking=release --enable-languages=c,c++,fortran,go,lto,objc,obj-c++ --disable-multilib
      - name: Compile source code
        run: |
          cd gcc-build-$VERSION
          sudo make -j16
      - name: Install gcc to Github Action
        run: |
          cd gcc-build-$VERSION
          sudo make install
      - name: Check gcc version
        run: | 
          ls /usr/bin -all -h
          gcc --version
          g++ --version
          gccgo --version
      - name: Check for C++ 23
        run: |
          touch main.cpp
          echo "#include<bits/stdc++.h>" >> main.cpp
          echo "using namespace std;" >> main.cpp
          echo "int main(){}" >> main.cpp
          g++ main.cpp -o main -std=c++2b
      - name: Make gcc deb
        run: |
          mkdir gcc-deb
          cd gcc-deb
          mkdir DEBIAN
          cd DEBIAN
          touch control
          echo Package: gcc >> control
          echo Version: $VERSION-$TYPE >> control
          echo Section: utils >> control
          echo Priority: optional >> control
          echo Depends: >> control
          echo Suggests: >> control
          echo Architecture: i386 >> control
          echo Maintainer: "LittleYang0531(https://github.com/LittleYang0531) >> control"
          echo Description: GNU Compilers >> control
          cd ../
          mkdir usr
          sudo cp /usr/bin ./ -r
          sudo cp /usr/lib ./ -r
          sudo cp /usr/share ./ -r
          cd ../../
          dpkg-deb gcc-deb gcc-$TYPE-$VERSION.deb
