# This is a basic workflow to help you get started with Actions

name: gcc-build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  VERSION: 13
  TYPE: basepoints

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - run: |
          echo Downloading gcc-$VERSION source code from mirror...
          wget https://github.com/gcc-mirror/gcc/archive/refs/tags/$TYPE/gcc-$VERSION.tar.gz -O gcc.tar.gz
          echo Extracting source code...
          tar -xvf gcc.tar.gz > /dev/null
          ls -all
          mv gcc-$TYPE-gcc-$VERSION gcc-$VERSION
          cd gcc-$VERSION
          echo Downloading dependences...
          ./contrib/download_prerequisites
          cd ..
          mkdir gcc-build-$VERSION
          cd gcc-build-$VERSION
          echo Checking system environment...
          ../gcc-$VERSION/configure --enable-checking=release --enable-languages=c,c++,fortran,go,lto,objc,obj-c++ --disable-multilib
          echo Compiling source code...
          sudo make -j16
          echo Installing gcc...
          sudo make install
          echo Checking gcc version...
          gcc --version
          ls /usr/bin -all -h
          
