name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clearing all the Files
      run: rm ./* -r
    - name: Cloning Codes
      run: git clone https://github.com/LittleYang0531/bilibili.git
    - name: Installing Dependence
      run: sudo apt install php php-curl zip -y
    - name: Downloading Your Photos
      run: php ./bilibili/spider.php 145944
    - name: Removing Codes
      run: rm bilibili -r
    - name: Zipping Your Files
      run: zip Photo.zip ./*
    - name: Uploading Your Photos
      uses: actions/upload-artifact@v2.2.4
      with:
        name: photo
        path: ./Photo.zip
    - name: Remove zip File
      run: rm Photo.zip
    - name: Initiative Git Repository
      run: git init
    - name: Add new Things to the Repository 
      run: git add -A
    - name: Commit the Repository
      run: git commit -m Upload
    - name: Upload Your Photos
      run: git push -f https://oauth2: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@github.com/LittleYang0531/Photo.git
    - name: Removing all the Things
      run: rm ./* -r
