name: ssh
on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: shaowenchen/debugger-action@v1
        name: debugger
        timeout-minutes: 30
        continue-on-error: true
        with:
          frp_server_addr: 139.198.113.238
          frp_server_port: 5443
          frp_token: jqhVb79zYjxZWGtw
          ssh_port: 24862
