name: ssh
on:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: shaowenchen/debugger-action@v1
        name: debugger
        timeout-minutes: 30
        continue-on-error: true
        with:
          frp_server_addr: frp.freefrp.net
          frp_server_port: 7000
          frp_token: freefrp.net
          ssh_port: 24862
