name: Get Photos From Pixel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clearing all the Files
      run: rm ./* -r
    - name: Cloning Codes
      run: git clone https://github.com/LittleYang0531/bilibili.git
    - name: Installing Dependence
      run: sudo apt install php php-curl zip -y
    - name: Create Directory
      run: mkdir output
    - name: Downloading Your Photos
      run: php ./bilibili/get.php
    - name: Removing Codes
      run: rm ./bilibili -r
    - name: Zipping Your Files
      run: zip Photo.zip ./output/*
    - name: Upload Your Photos
      uses: actions/upload-artifact@v2.2.4
      with: 
        name: photo
        path: ./Photo.zip
    - name: Removing all the Things
      run: rm ./* -r
