name: Get Photos From Pixel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clearing all the Files
      run: rm ./* -r
    - name: Cloning Codes
      run: git clone https://github.com/LittleYang0531/bilibili.git
    - name: Installing Dependence
      run: sudo apt install php php-curl zip -y
    - name: Downloading Your Photos
      run: php ./bilibili/spider.php 145944
    - name: Removing Codes
      run: rm ./bilibili -r
    - name: Zipping Your Files
      run: zip Photo.zip ./*
    - name: Removing all the Things
      run: rm ./* -r
