# This is a basic workflow to help you get started with Actions

name: PlanetScale

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  VERSION: 13
  TYPE: basepoints

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Install Dependence
        run: |
          sudo apt update
          sudo apt install mariadb-client mariadb-server -y
          HOST="3yshbbnym7dz.ap-""northeast-2.psdb.cloud"
          PORT=3306
          USER="r6bdz7""mpxezj"
          PASSWD="pscale_pw_t2K2QjT6t""wo4BqWs2i8xZOzuYh5YE0cyiLTjo2DJisg"
          DB="type""cho"
          mysql -u"$HOST" -p"$PASSWD" -h"$HOST" -D"$DB" -P"$PORT" -e"select * from typecho_visitors LIMIT 200" --ssl-mode=VERIFY_IDENTITY --ssl-ca=/etc/ssl/certs/ca-certificates.crt
